# Generated by Django 3.2.4 on 2021-06-20 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_date', models.DateField(default=django.utils.timezone.now)),
                ('learn_time', models.TimeField(default=django.utils.timezone.now)),
                ('learn_status', models.CharField(default='P', max_length=1)),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
                ('apply_time', models.TimeField(default=django.utils.timezone.now)),
                ('apply_status', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LearnNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(default='')),
                ('tokens', models.TextField(default='')),
                ('target', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RealNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(default='')),
                ('tokens', models.TextField(default='')),
                ('target', models.IntegerField(default=0)),
            ],
        ),
    ]
